name: 'Add to Release'

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout  the source code from GitHub'
      uses: actions/checkout@master
    - name: 'Build Mod with HEMTT'
      uses: gruppe-adler/action-release-with-hemtt@1.0
      id: build
    - name: 'Upload to release'
      uses: Shopify/upload-to-release
        with:
          name: ${{ steps.build.outputs.zip_name }}
          path: ${{ steps.build.outputs.zip_path }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/zip
