name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout repo from git'
      uses: actions/checkout@master
    - name: 'Build Mod with HEMTT'
      uses: DerZade/gh-action-build-hemtt-mod@master
      id: build
    - name: 'Upload artifact'
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.build.outputs.zip_name }}
        path: ${{ steps.build.outputs.zip_path }}
